import * as fs from 'node:fs';
import * as path from 'node:path';

export interface DiscoveredFile {
  filePath: string;
  relativePath: string;
  baseName: string;
}

export interface DiscoveryOptions {
  pattern?: string;
  rootDir?: string;
  exclude?: string[];
}

const DEFAULT_PATTERN = '**/*.testify.tsx';
const DEFAULT_EXCLUDE = ['node_modules', 'dist', '.git', 'ios', 'android'];

export function discoverTestifyFiles(
  options: DiscoveryOptions = {},
): DiscoveredFile[] {
  const {
    pattern = DEFAULT_PATTERN,
    rootDir = process.cwd(),
    exclude = DEFAULT_EXCLUDE,
  } = options;

  const files: DiscoveredFile[] = [];
  const visited = new Set<string>();

  function walkDir(dir: string) {
    if (visited.has(dir)) return;
    visited.add(dir);

    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        if (
          !exclude.some((ex) => entry.name === ex || entry.name.startsWith('.'))
        ) {
          walkDir(fullPath);
        }
      } else if (entry.isFile()) {
        const relativePath = path.relative(rootDir, fullPath);
        if (matchesPattern(relativePath, pattern)) {
          const baseName = deriveBaseName(relativePath);
          files.push({
            filePath: fullPath,
            relativePath,
            baseName,
          });
        }
      }
    }
  }

  walkDir(rootDir);
  return files.sort((a, b) => a.baseName.localeCompare(b.baseName));
}

function matchesPattern(relativePath: string, pattern: string): boolean {
  // Normalize path separators
  const normalizedPath = relativePath.replace(/\\/g, '/');
  const normalizedPattern = pattern.replace(/\\/g, '/');

  // Convert glob pattern to regex by processing character by character
  let regexPattern = '';
  let i = 0;
  while (i < normalizedPattern.length) {
    const char = normalizedPattern[i];
    const nextChar = normalizedPattern[i + 1];

    if (char === '*' && nextChar === '*') {
      // ** - match any path segments
      if (normalizedPattern[i + 2] === '/') {
        // **/ - match zero or more directories
        regexPattern += '(?:.*/)?';
        i += 3;
      } else {
        // ** at end - match anything
        regexPattern += '.*';
        i += 2;
      }
    } else if (char === '*') {
      // * - match any characters except /
      regexPattern += '[^/]*';
      i += 1;
    } else if (char === '?') {
      // ? - match single character except /
      regexPattern += '[^/]';
      i += 1;
    } else if ('.+^${}()|[]\\'.includes(char)) {
      // Escape regex special characters
      regexPattern += `\\${char}`;
      i += 1;
    } else {
      regexPattern += char;
      i += 1;
    }
  }

  const regex = new RegExp(`^${regexPattern}$`);
  return regex.test(normalizedPath);
}

function deriveBaseName(relativePath: string): string {
  // Remove extension and .testify suffix
  // e.g., "src/components/Button.testify.tsx" -> "Button"
  const withoutExt = relativePath.replace(/\.testify\.tsx?$/, '');
  const parts = withoutExt.split(path.sep);

  // Remove common prefixes like src, components, testify
  const skipPrefixes = ['src', 'components', 'testify', 'tests', '__tests__'];
  while (parts.length > 1 && skipPrefixes.includes(parts[0])) {
    parts.shift();
  }

  return parts.join('/');
}

export function generateRegistryCode(
  files: DiscoveredFile[],
  registryPath: string,
): string {
  const imports: string[] = [];
  const spreads: string[] = [];
  const usedNames = new Set<string>();

  for (const file of files) {
    const importPath = getRelativeImportPath(registryPath, file.filePath);
    let safeNameBase = file.relativePath
      .replace(/\\/g, '/')
      .replace(/\.tsx?$/, '')
      .replace(/[^a-zA-Z0-9_]/g, '_');

    if (!/^[a-zA-Z_]/.test(safeNameBase)) {
      safeNameBase = `_${safeNameBase}`;
    }

    let safeName = `${safeNameBase}Variants`;
    let suffix = 2;
    while (usedNames.has(safeName)) {
      safeName = `${safeNameBase}Variants_${suffix}`;
      suffix += 1;
    }
    usedNames.add(safeName);

    imports.push(`import ${safeName} from '${importPath}';`);
    spreads.push(`  ...${safeName},`);
  }

  return `// Auto-generated by testify - do not edit manually
import { createRegistry } from 'react-native-testify';

${imports.join('\n')}

export default createRegistry({
${spreads.join('\n')}
});
`;
}

function getRelativeImportPath(from: string, to: string): string {
  const fromDir = path.dirname(from);
  let relative = path.relative(fromDir, to);
  // Normalize to POSIX-style paths (forward slashes) for valid ES module specifiers
  relative = relative.replace(/\\/g, '/');
  // Remove extension for imports
  relative = relative.replace(/\.tsx?$/, '');
  // Ensure relative path starts with ./
  if (!relative.startsWith('.')) {
    relative = `./${relative}`;
  }
  return relative;
}
